sonar.projectKey=green-trails_backend
sonar.organization=green-trails
sonar.host.url=https://sonarcloud.io

sonar.sources=backend/src/main/java
sonar.tests=backend/src/test/java
sonar.java.binaries=backend/target/classes
sonar.java.test.binaries=backend/target/test-classes
sonar.java.libraries=backend/target/dependency/*

sonar.coverage.jacoco.xmlReportPaths=backend/target/site/jacoco/jacoco.xml

sonar.exclusions=**/entities/**,**/enums/**,**/*Exception.class,**/BackendApplication.class,**/ArchiviazioneProperties.class,**/CorsConfig.class
